# Generated by Django 5.0 on 2024-02-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetable',
            old_name='price',
            new_name='time',
        ),
    ]
